//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomain) DeepCopyInto(out *ComputeDomain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomain.
func (in *ComputeDomain) DeepCopy() *ComputeDomain {
	if in == nil {
		return nil
	}
	out := new(ComputeDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainChannelSpec) DeepCopyInto(out *ComputeDomainChannelSpec) {
	*out = *in
	out.ResourceClaimTemplate = in.ResourceClaimTemplate
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainChannelSpec.
func (in *ComputeDomainChannelSpec) DeepCopy() *ComputeDomainChannelSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainList) DeepCopyInto(out *ComputeDomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainList.
func (in *ComputeDomainList) DeepCopy() *ComputeDomainList {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainNode) DeepCopyInto(out *ComputeDomainNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainNode.
func (in *ComputeDomainNode) DeepCopy() *ComputeDomainNode {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainResourceClaimTemplate) DeepCopyInto(out *ComputeDomainResourceClaimTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainResourceClaimTemplate.
func (in *ComputeDomainResourceClaimTemplate) DeepCopy() *ComputeDomainResourceClaimTemplate {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainResourceClaimTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainSpec) DeepCopyInto(out *ComputeDomainSpec) {
	*out = *in
	if in.Channel != nil {
		in, out := &in.Channel, &out.Channel
		*out = new(ComputeDomainChannelSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainSpec.
func (in *ComputeDomainSpec) DeepCopy() *ComputeDomainSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainStatus) DeepCopyInto(out *ComputeDomainStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]*ComputeDomainNode, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ComputeDomainNode)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainStatus.
func (in *ComputeDomainStatus) DeepCopy() *ComputeDomainStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainStatus)
	in.DeepCopyInto(out)
	return out
}
